spring:
  application:
    name: fridgemate-api
  
  profiles:
    active: dev
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

# 로깅 설정
logging:
  level:
    com.fridgemate: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# CORS 설정
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

# AI 설정
ai:
  provider: rule # rule | llm
  llm:
    api-key: ${LLM_API_KEY:}
    base-url: ${LLM_BASE_URL:}

---
# 개발 환경
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fridgemate
    username: fridgemate_user
    password: fridgemate_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    show-sql: true

---
# Docker 환경
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/fridgemate}
    username: ${SPRING_DATASOURCE_USERNAME:fridgemate_user}
    password: ${SPRING_DATASOURCE_PASSWORD:fridgemate_pass}
    driver-class-name: org.postgresql.Driver

---
# 테스트 환경
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

# MySQL 대체 설정 예시 (필요시 활성화)
# ---
# spring:
#   config:
#     activate:
#       on-profile: mysql
#   datasource:
#     url: jdbc:mysql://localhost:3306/fridgemate?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: fridgemate_user
#     password: fridgemate_pass
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
